version: '2'

services:
  nginx:
    image: nginx:alpine
    restart: always
    links:
      - fpm5-6-23
      - fpm7-0-8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/enabled:/etc/nginx/conf.d
      - ./nginx/snippets:/nginx/snippets
      - ./nginx/certificates:/nginx/certificates
    volumes_from:
      - data

  fpm5-6-23:
    image: php:5.6.23-fpm-alpine
    restart: always
    volumes_from:
      - data

  fpm7-0-8:
    image: php:7.0.8-fpm-alpine
    restart: always
    volumes_from:
      - data

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    # ports:
    #   - "8080:80"

  data:
    image: alpine:latest
    command: echo "READY!!!"
    volumes:
      - ./vhosts:/vhosts
      - ./tmp:/tmp
