version: '2.4'

services:
  nginx:
    image: nginx:alpine
    restart: always
    links:
      - fpm-ext7-0-8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/enabled:/etc/nginx/conf.d
      - ./nginx/snippets:/nginx/snippets
      - ./nginx/certificates:/nginx/certificates
    volumes_from:
      - data
    networks:
      - monres
      
  fpm-ext7-0-8:
    build:
      context: ./dockerfiles
      dockerfile: php-7-0-8-fpm-ext-alpine.Dockerfile
    restart: always
    volumes_from:
      - data

  db:
    image: harianto/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/storage:/var/lib/mysql

  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db

  bind9:
    image: sameersbn/bind:9.16.1-20200524
    restart: always
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
      - ./bind:/data
    networks:
      - monres

  data:
    image: alpine:latest
    command: echo "READY!!!"
    volumes:
      - ./vhosts:/vhosts
      - ./tmp:/tmp

networks:
  monres: