version: '2'

services:
  nginx:
    image: nginx:alpine
    restart: always
    links:
      - fpm-ext7-0-8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/enabled:/etc/nginx/conf.d
      - ./nginx/snippets:/nginx/snippets
      - ./nginx/certificates:/nginx/certificates
    volumes_from:
      - data
      
  fpm-ext7-0-8:
    build:
      context: ./dockerfiles
      dockerfile: php-7-0-8-fpm-ext-alpine.Dockerfile
    restart: always
    volumes_from:
      - data

  db:
    image: harianto/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/storage:/var/lib/mysql

  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    # ports:
    #   - "8080:80"

  bind9:
    image: sameersbn/bind:9.16.1-20200524
    restart: always
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
      - ./bind:/data
    volumes_from:
      - data

  ftp:
    image: bluefoxicy/proftpd
    cap_drop:
      - net_raw
      - mknod
      - setpcap
      - setfcap
      - fowner
      - dac_override
    environment:
      PROFTPD_PASSIVE_PORTS: "50000-50030"
      PROFTPD_TLS: on
      PROFTPD_AUTH_ORDER: "mod_auth_file.c"
    ports:
      - "21:21"
      - "50000-50030:50000-50030"
    volumes:
      # FTP directory
      - /var/docker/controlesr/ftp/site1/files/:/var/ftp
      # Configuration
      - /var/docker/controlesr/ftp/site1/config/auth.d/:/etc/proftpd/auth.d/
      - /var/docker/controlesr/ftp/site1/config/conf.d/:/etc/proftpd/conf.d/
      # keeping user.d/authfile/passwd and user.d/authfile/group
      - /var/docker/controlesr/ftp/site1/config/user.d/:/etc/proftpd/user.d/
      # ssl certificates
      - /etc/ssl/certs/example.com.crt:/etc/ssl/certs/proftpd.crt:ro
      - /etc/ssl/certs/example.com.chain.crt:/etc/ssl/certs/chain.crt:ro
      - /etc/ssl/private/example.com.key:/etc/ssl/private/proftpd.key:ro

  data:
    image: alpine:latest
    command: echo "READY!!!"
    volumes:
      - ./vhosts:/vhosts
      - ./tmp:/tmp