version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      DB_USER: test1
      DB_PASSWORD: test1
      DB_NAME: test1
    volumes:
      - ./db/storage:/var/lib/mysql