version: '3.7'

services:
  proftpd:
    image: kibatic/proftpd
    network_mode: "host"
    restart: unless-stopped
    environment:
      FTP_LIST: "romain:1234;r0m41nUser:r0m41nMdp"
    volumes:
      - "/var/docker/controlesr/vhosts/heberg/subdomains/theo:/home/theo"